# -*- coding: utf-8 -*-
"""tryout.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lpl8w-V4FdpFsuhBeLJYOJup0wXuTWMJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import joblib

from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import os
import mlflow
import sagemaker_mlflow
import mlflow.sklearn
import subprocess


def load_data(data_path: str) -> pd.DataFrame:
    """
        - Taken as function because, Path is now a parameter, not hardcoded
        - CI pipeline passess the absolute path via args/env vars
        - Can be unit tested independently
    """
    df = pd.read_csv(data_path)
    return df

def preprocess(df: pd.DataFrame):
    """
        - preprocessing logic changes often, keeping it isolated makes it easy.
    """
    obj_cols = df.select_dtypes(include=['object']).columns.tolist()
    encoded_df = pd.get_dummies(df, columns=obj_cols, drop_first=True, dtype=int)

    X = encoded_df.drop(columns=['charges'])
    y = encoded_df['charges']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    continuous_cols = ['age', 'bmi', 'children']
    ct = ColumnTransformer([('scale', MinMaxScaler(), continuous_cols)], remainder='passthrough') # initializing the transformer which will apply normalization to continuous_cols
    ct.set_output(transform = "pandas") # ct will reorder the columns. Add this to fix column names

    X_train_scaled = ct.fit_transform(X_train) # transforming data
    X_test_scaled = ct.transform(X_test)

    return X_train_scaled, X_test_scaled, y_train, y_test, ct

def train_model(X_train, y_train) -> LinearRegression:        
    linear_model = LinearRegression()
    linear_model.fit(X_train, y_train)
    return linear_model


def evaluate_model(model, X_test, y_test) -> dict:
    """
    WHY return a dict?
      - The CI pipeline / MLflow can pick up these metrics and log them to the registry.      
    """

    predictions = model.predict(X_test)
    metrics = {"mae": mean_absolute_error(y_test, predictions), "r2_score": r2_score(y_test, predictions)}
    return metrics

def save_artifacts(model, scaler, model_dir:str):
    """
    WHY save the scaler too?
      - predict.py needs to scale NEW input data the same way training data was scaled.
      - Without saving ct (the scaler), predict.py has no way to reproduce that transformation.
    """
    
    os.makedirs(model_dir, exist_ok=True) #command to create folder(even nested folders) # model_dir -> folder path   # if folder already exists, no changes
    joblib.dump(model, os.path.join(model_dir, "model.pkl"))
    joblib.dump(scaler, os.path.join(model_dir, "scaler.pkl"))
    print(f"Artifacts saved to {model_dir}")

def main():
    """
      - CI calls: `python src/train.py` → runs main().
      - Tests import `from src.train import preprocess` → main() does NOT run.
    """
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    # /opt/ml/code   <- base_dir in container

    data_path = os.path.join(BASE_DIR, "data", "insurance.csv")

    # In container, whether training data is read directly from the source or 

    model_dir = os.getenv("SM_MODEL_DIR", os.path.join(BASE_DIR, "models"))

    #(native sagemaker env variable) SM_MODEL_DIR -> /opt/ml/model 

    mlflow_uri = os.getenv("MLFLOW_URI")
    mlflow.set_tracking_uri(mlflow_uri)

    mlflow.set_experiment("Insurance charges prediction")
    # To create or use a workspace for logging experiment details
    with mlflow.start_run():
        df = load_data(data_path)

        sagemaker_job_name = os.getenv("TRAINING_JOB_NAME", "local-run")
        mlflow.log_param("sagemaker_job_name", sagemaker_job_name)
        # Log git commit hash
        commit_hash = subprocess.check_output(["git", "rev-parse", "HEAD"]).decode().strip()
        mlflow.log_param("git_commit_hash", commit_hash)

        # log dataset information
        mlflow.log_param("dvc_md5", "1c1b39fc9cc5051cf793e8709aaac8b5")
        mlflow.log_param("dataset", data_path)
        mlflow.log_param("num_rows", len(df))
        mlflow.log_param("num_cols", len(df.columns))
        mlflow.log_param("target_column", "charges")

        # log experiment parameters
        mlflow.log_param("model", "LinearRegression")
        mlflow.log_param("scaler", "MinMaxScaler")
        mlflow.log_param("test_size", 0.2)
        mlflow.log_param("random_state", 42)

        X_train, X_test, y_train, y_test, scaler = preprocess(df)
        model = train_model(X_train, y_train)
        metrics = evaluate_model(model, X_test, y_test)

        # log metrics
        mlflow.log_metrics({
            "mae": metrics['mae'],
            "r2_score": metrics['r2_score']
        })

        save_artifacts(model, scaler, model_dir)

        # log artifacts
        # mlflow.log_artifacts(model_dir) # bulk upload all the contents in the folder 'model_dir'
        mlflow.log_artifact(os.path.join(model_dir, "scaler.pkl"))
        # mlflow.log_artifact(os.path.join(model_dir, "model.pkl"))

        print(f"MAE = {metrics['mae']:.2f}")
        print(f"R2 score = {metrics['r2_score']:.4f}")

        # to create deployable MLflow model
        mlflow.sklearn.log_model(
            model, 
            name="model_deploy", 
            registered_model_name = "InsuranceChargesModel",  # to register this model in mlflow registry in mlflow server. Creates/increments versions in registry 
            pip_requirements=["scikit-learn", "pandas", "numpy"]
        )
        # model_deploy is the folder name inside MLflow run's artifact storage

if __name__ == "__main__":
    main()    