# Triggered manually from Github Actions UI after human approves the model in MLflow UI

name: CD - Deploy approved model to the sagemaker

on: 
  workflow_dispatch:
    
    #Inputs commented out, as not needed anymore. As the production model is obtained by querying directly to mlflow registry

    # inputs: 
    #   image_tag:  # 'image_tag' is one input. You can name any input
    #     description: "Inference image tag to be deployed"
    #     required: True

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt 

      # - name: run tests
      #   run: pytest

      # - name: Login to Dockerhub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{vars.DOCKER_USERNAME}}
      #     password: ${{secrets.DOCKER_PASSWORD}}
      
      # - name: Build docker image
      #   run: docker build -f docker/inference/Dockerfile -t ${{vars.DOCKER_USERNAME}}/ml-inference:${{github.event.inputs.image_tag}} .

      # - name: Upload the image to Dockerhub
      #   run: docker push ${{vars.DOCKER_USERNAME}}/ml-inference:${{github.event.inputs.image_tag}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
        
      - name: Login into AWS ECR 
        id: login-ecr 
        uses: aws-actions/amazon-ecr-login@v2 

      - name: Build & push images 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: production/mlops-inference 
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f docker/inference/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Deploy: reads approved model from Registry -> finds model.tar.gz -> creates or updates endpoint
      - name: Deploy production model to Sagemaker endpoint
        env:  
          MLFLOW_URI: ${{ vars.MLFLOW_URI }}          
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/production/mlops-inference:${{ github.sha }}
          # Not needed as they are already configured
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}          
          SAGEMAKER_OUTPUT_PATH: ${{ vars.SAGEMAKER_OUTPUT_PATH }}
          SAGEMAKER_ROLE: ${{ vars.SAGEMAKER_ROLE_ARN }}  
          SAGEMAKER_ENDPOINT: ${{ vars.SAGEMAKER_ENDPOINT}}  
      
        run: python src/pipeline/deploy.py              